# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - ./node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm audit
      - run: npm lint

      - setup_remote_docker
      - deploy:
          name: Build and deploy docker image
          command: |
            npm run build
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t zackmattor/aurora-app:latest .
            docker tag zackmattor/aurora-app:latest zackmattor/aurora-app:$CIRCLE_SHA1
            docker push zackmattor/aurora-app:$CIRCLE_SHA1
            docker push zackmattor/aurora-app:latest
